
lib_path = -L/home/gxk/github/build/debug-install/lib
header_path = -I/home/gxk/github/build/debug-install/include
LIBS=-lmuduo_net -lmuduo_base -lpthread
CFLAGS=$(lib_path) $(header_path)
CC=g++
start:
		$(CC)  $(CFLAGS) Counter.cc $(LIBS)

# main.o:main.cc
# 		$(CC)  $(CFLAGS) -c main.cc

# echo.o: echo.cc echo.h
# 		$(CC) $(CFLAGS) -c echo.cc

